.\" Manpage for egc.
.\" Contact cpmachado@protonmail.com to correct errors or typos.
.TH man 1 "8 February 2024" "1.0" "egc man page"
.SH NAME
egc \- compute unitary fraction expansion of an r in ]0, 1[
.SH SYNOPSIS
egc [-h][-v] [-n NUMERATOR] [-d DENOMINATOR]
.SH DESCRIPTION
TBD
.SH OPTIONS
.TP
.BR \-h
display help and exit
.TP
.BR \-v
display version and exit
.TP
.BR \-n " " NUMERATOR
set numerator of fraction
.TP
.BR \-d " " DENOMINATOR
set denominator of fraction
.SH BUGS
No known bugs.
.SH AUTHOR
Carlos Pinto Machado (cpmachado@protonmail.com)
